### ISSUE TITLE
Archivable conditions

### ISSUE THREAD

**Issue by ericraio** [Sign2Pay/mongoid-archivable#2]
Am I able to archive older records if a query returns a set of records over X?

I have a chat room, and i want to start archiving messages if the room has over 10,000 messages.

**Comment by tilsammans** [comment]
I'm afraid this gem won't be able to help you. This gem listens for the destroy message on the document and then it moves it into the archive, instead of destroying it.

What you want is a process that watches the _collection_ and then moves the oldest messages into an archive. I'd possibly just go with a cron job that runs once every hour.
